services:
  postgres:
    image: postgres:13
    restart: on-failure
    environment:
      POSTGRES_USER: notification_service
      POSTGRES_PASSWORD: notification_service
      POSTGRES_DB: notification_service
    ports:
      - 5434:5432
    #        networks:
    #            - helsinki
    volumes:
      - pgdata:/var/lib/postgresql@13/data
    container_name: notification_service-db

  keycloak:
    image: quay.io/keycloak/keycloak
    restart: on-failure
    env_file:
      - keycloak/docker-compose.keycloak.env
    command:
      - start-dev
      - --http-port=8180
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
      - --import-realm
    #        networks:
    #          - helsinki
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro
    ports:
      - 8180:8180
    container_name: notification-service-keycloak

  django:
    build:
      context: .
      target: ${DOCKER_TARGET:-development}
    restart: on-failure
    env_file:
      - docker-compose.env
    volumes:
      - .:/app
      # Prevent sharing the following directories between host and container
      # to avoid ownership and/or platform issues:
      - /app/.ruff_cache
      - /app/.pytest_cache
    #        networks:
    #            - helsinki
    ports:
      - 8081:8081
      - 8000:8000
    depends_on:
      - postgres
      - keycloak
    container_name: notification_service-api

  validator:
    image: openapitools/openapi-generator-cli
    command: validate -i /api/openapi.yaml
    container_name: notification_service-api-openapi-validator
    volumes:
      - ./openapi.yaml:/api/openapi.yaml

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8082:8082
    environment:
      PORT: "8082"
      SWAGGER_JSON: "/api/openapi.yaml"
    container_name: notification_service-api-swagger-ui
    volumes:
      - ./openapi.yaml:/api/openapi.yaml

volumes:
  pgdata:
    driver: local
