# Generated by Django 5.1.11 on 2025-08-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.CharField(max_length=50)),
                ('number_field', models.IntegerField()),
                ('boolean_field', models.BooleanField(default=False)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
