# Generated by Django 5.2.11 on 2026-02-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit_log", "0002_dummytestmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuditLogEntry",
        ),
    ]
