# Generated by Django 5.2.11 on 2026-02-17 10:48

from django.db import migrations


def convert_messages_dict_to_list(apps, schema_editor):
    """
    Convert DeliveryLog.report['messages'] from dict to list format.

    Old format: {"messages": {"+358401231234": {"converted": "+358401231234", "status": "CREATED"}}}
    New format: {"messages": [{"converted": "+358401231234", "status": "CREATED"}]}
    """
    DeliveryLog = apps.get_model("api", "DeliveryLog")

    updated_count = 0
    for log in DeliveryLog.objects.all():
        if not log.report:
            continue

        messages = log.report.get("messages")
        if not messages:
            continue

        # Check if already in list format (idempotent migration)
        if isinstance(messages, list):
            continue

        # Convert dict to list
        if isinstance(messages, dict):
            new_messages = []
            for phone, message_data in messages.items():
                # Just use the message data as-is (converted field already has phone)
                new_messages.append(message_data)

            log.report["messages"] = new_messages
            log.save(update_fields=["report"])
            updated_count += 1

    print(f"Converted {updated_count} DeliveryLog records from dict to list format")


def reverse_messages_list_to_dict(apps, schema_editor):
    """
    Reverse migration: Convert list back to dict format.
    """
    DeliveryLog = apps.get_model("api", "DeliveryLog")

    updated_count = 0
    for log in DeliveryLog.objects.all():
        if not log.report:
            continue

        messages = log.report.get("messages")
        if not messages:
            continue

        # Check if already in dict format
        if isinstance(messages, dict):
            continue

        # Convert list to dict
        if isinstance(messages, list):
            new_messages = {}
            for message in messages:
                # Use converted or destination field as the key
                phone = message.get("converted") or message.get("destination")
                if phone:
                    new_messages[phone] = message

            log.report["messages"] = new_messages
            log.save(update_fields=["report"])
            updated_count += 1

    print(f"Reverted {updated_count} DeliveryLog records from list to dict format")


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_deliverylog_report"),
    ]

    operations = [
        migrations.RunPython(
            convert_messages_dict_to_list,
            reverse_code=reverse_messages_list_to_dict,
        ),
    ]
